{
    "name": "IDX HRM 台灣在地化 HR 模組",
    "version": "19.0.1.0.0",
    "category": "Human Resources",
    "summary": "Odoo 19 台灣勞基法 HR 客製模組（勞健保、所得稅、出勤、加班、特休）",
    "author": "IDX",
    "license": "LGPL-3",
    "depends": [
        "hr",
        "hr_holidays",
        "hr_attendance",
        "payroll",
        "mail",
    ],
    "data": [
        "security/groups_overtime.xml",
        "security/ir.model.access.csv",
        "security/ir_record_rules.xml",
        "data/ir_cron.xml",
        "data/hr_overtime_sequence.xml",
        "data/hr_leave_type_data.xml",
        "data/hr_overtime_type_data.xml",
        "data/hr_payroll_data.xml",
        "views/res_config_settings_views.xml",
        "views/hr_attendance_setting_views.xml",
        "views/hr_late_early_criterion_views.xml",
        "views/hr_overtime_views.xml",
        "views/hr_overtime_config_settings_views.xml",
        "views/hr_labor_health_insurance_views.xml",
        "views/hr_income_tax_pivot_views.xml",
        "views/hr_annual_leave_views.xml",
        "views/hr_holiday_type_setting_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_dependents_views.xml",
        "views/hr_attendance_ext_views.xml",
        "views/hr_overtime_request_form.xml",
        "views/hr_overtime_manager_views.xml",
        "views/resource_calendar_views_ext.xml",
        "views/hr_public_holiday_wizard_views.xml",
        "views/menus.xml",
    ],
    "application": False,
    "installable": True,
}
