from . import test_res_config_settings
from . import test_hr_attendance_setting
from . import test_hr_late_early_criterion
from . import test_hr_overtime
from . import test_hr_labor_health_insurance
from . import test_hr_income_tax_pivot
from . import test_hr_annual_leave
from . import test_hr_holiday_type_setting
from . import test_cron_methods
