from . import res_config_settings
from . import hr_attendance_setting
from . import hr_late_early_criterion
from . import hr_overtime
from . import hr_labor_health_insurance
from . import hr_income_tax_pivot
from . import hr_annual_leave
from . import hr_holiday_type_setting
from . import cron_methods
from . import hr_overtime_calculation
from . import hr_employee
from . import hr_employee_foreign
from . import hr_contract
from . import hr_dependents
from . import hr_attendance_ext
from . import hr_attendance_abnormal
